---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r,echo=T}
Sys.setlocale(locale="English")
library(data.table)
library(ggplot2)
library(magrittr)
library(knitr)
activity=read.csv("./input/activity.csv") %>% setDT
summary(activity)
#remove na
#activity=activity[!is.na(steps)]
```


## What is mean total number of steps taken per day?
```{r,echo=T}
#sum transformation
activityPerDay=activity[!is.na(steps),.("steps_per_day"=sum(steps,na.rm = T))
                        ,by=date]
#histogram
ggplot(data=activityPerDay)+geom_histogram(aes(steps_per_day))
#summary
out1=activityPerDay[,.("means"=mean(steps_per_day,na.rm = T),
                      "medians"=median(steps_per_day,na.rm = T)
)]
out1
```



## What is the average daily activity pattern?
```{r,echo=T}
activityPerInterval=activity[,.("mean_steps"=mean(steps,na.rm = T)),by=interval]
ggplot(data=activityPerInterval)+geom_line(aes(x=interval,y=mean_steps))
activityPerInterval[mean_steps==max(mean_steps),interval]
```


## Imputing missing values
```{r,echo=T}
#number of missing cases
activity[is.na(steps),.N]
# changing NAs to means by interval
activity_fill=activityPerInterval[activity,on=c("interval")]
#lets have them as integers also
activity_fill[is.na(steps),steps:=round(mean_steps) %>% as.integer()]

#sum transformation
activityFillPerDay=activity_fill[!is.na(steps),
                               .("steps_per_day"=sum(steps,na.rm = T))
                               ,by=date]
#histogram
ggplot(data=activityFillPerDay)+geom_histogram(aes(steps_per_day))
#summary
out2=activityFillPerDay[,.("means"=mean(steps_per_day,na.rm = T),
                          "medians"=median(steps_per_day,na.rm = T)
)]
out2
#mean and median decreased

```
After filling missing values estimations of mean and median for total steps per day dropped insignificantly (lesser than 0.05%):
```{r,echo=T}
(out2/out1-1)*100
```



## Are there differences in activity patterns between weekdays and weekends?
```{r,echo=T}

activity_fill[,weekend:=ifelse(date %>% strftime("%w") %in% c(0,6),"weekend","weekday") 
                        %>% factor]

activityPerIntervalWknd=activity_fill[,.("mean_steps"=mean(steps,na.rm = T)),by=.(weekend,interval)]

ggplot(data=activityPerIntervalWknd,aes(x=interval,y=mean_steps) ) + geom_line() +
  facet_grid(weekend~.)
```


